### ISSUE TITLE
Tradleconf update fails

### ISSUE THREAD

**Issue by martinheidegger** [tradle/tradleconf#25]
via @spwilko
```
% tradleconf update -c
Updating! To roll back, run:
tradleconf update-manually --template-url ".../compiled-cloudformation-template.json" --stack-parameters "params-3.1.1-rc.14-1642611680013.json"

· loading release 3.1.1-rc.18, grab a coffee...
TypeError: Cannot read property 'ignore' of undefined
    at Updater.<anonymous> (@tradle/conf/lib/node_modules/@tradle/conf/src/update.ts:211:20)
    at Generator.throw (<anonymous>)
    at rejected (@tradle/conf/lib/node_modules/@tradle/conf/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by martinheidegger** [comment]
This problem was a bit deeper than I expected. Some investigation 🕵️ and trial & error was necessary to figure out what is going on here.

This is the line that causes the error according to the message:

https://github.com/tradle/tradleconf/blob/c30e2b53187d8c5031b5a1cd3f7cb2ec158edd5b/src/update.ts#L211

It clearly uses `Errors.ignore`, which is part of [`@tradle/errors`](https://github.com/tradle/errors) for a long time now. The `update.ts` file itself has not been touched in 3 years but we know It has worked more recently.

It must have been part of the dependency update. And yes: it turns out that in [c70a208](https://github.com/tradle/tradleconf/commit/c70a2087ced80079fa0112c3dd40b277da52e8d6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L38) I updated `@tradle/errors` from 1.1.0 to [2.0.0](https://github.com/tradle/errors/releases/tag/v2.0.0). Version 2 which was released by Mark also 3 years ago. Back when I did the update, I did look in the changes and all that changes was that the code was now written in TypeScript and then compiled into JavaScript. All the functions that we used before are still available. The compiler passed. It should have gotten only better,  so why does this error occur now?

I looked at the compiled code of `@tradle/conf` and found this:

```js
// ...
const errors_1 = tslib_1.__importDefault(require("@tradle/errors"));
// ...
                            errors_1.default.ignore(err, errors_2.Errors.NotFound);
```

Typescript - during compilation - looks at the import statement of the code in the npm package and decided it uses the `default` property for when accessing the properties statement. It turns out when the package contains type declaration files _(which are in `@tradle/errors@2.0.0`)_ then `import Errors from '@tradle/errors'` will be turned from `const errors_1 = require('@tradle/errors')` to the `__importDefault` variant. But the code compiled by typescript does not create the `default` property making it `undefined`.

The reason why TypeScript allows us to type `import Error from '@tradle/errors'` is because we have following setting activated:

https://github.com/tradle/tradleconf/blob/c30e2b53187d8c5031b5a1cd3f7cb2ec158edd5b/tsconfig.json#L8

Without this setting we would have needed to use `import Error = require('@tradle/errors')`. Which is perfectly fine and would have prevented the issue at hand.

I tried a variety of `tsconfig.json` settings in this repository to see if I could convince the typescript compiler to drop the `.default` property, but to no avail. Instead I figured out that we can change `@tradle/errors` to make it have the `.default` property.

In https://github.com/tradle/errors/commit/52cfbaa62fdf0c648c097229f7efa156d536e016 I made sure that all exported statements are additionally available. This way, both with the setting enabled and disabled we can use the `@tradle/errors` package.

I publish [`@tradle/errors@2.0.1`](https://github.com/tradle/errors/commit/325c420ee500a57b271571701df9516fa1c23a010) and published [`@tradle/conf@1.15.3`](https://github.com/tradle/tradleconf/commit/c30e2b53187d8c5031b5a1cd3f7cb2ec158edd5b) that should contain the fix for this particular error.

### Lessons learned:

- Do not enable `esModuleInterop` in typescript. It is dangerous.
- Use `import package = require('package')` syntax when loading CommonJS packages/modules.
- With `esModuleInterop` enabled we need to look out if packages we update suddenly supply typescript declaration files.  They are usually not considered breaking changes but could break our code nevertheless.
