### ISSUE TITLE
Tradleconf@1.51.3 update fails

### ISSUE THREAD

**Issue by spwilko** [tradle/tradleconf#26]
tradleconf update -c
TypeError: Cannot read property 'tag' of undefined
    at Updater.<anonymous> (/Users/simonwilkinson/.volta/tools/image/packages/@tradle/conf/lib/node_modules/@tradle/conf/src/update.ts:172:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/simonwilkinson/.volta/tools/image/packages/@tradle/conf/lib/node_modules/@tradle/conf/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by martinheidegger** [comment]
This error occurs when the mycloud is disabled.
